# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - '**/readme.md'
    include:
      - cli/

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'

- task: CopyFiles@2
  displayName: 'Copy cli files to dist'
  inputs:
    SourceFolder: $(Build.SourcesDirectory)/cli
    Contents: |
      **/*
      !node_modules/**
    TargetFolder: $(Build.SourcesDirectory)/cli/dist

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'cli'
    PathtoPublish: '$(Build.SourcesDirectory)/cli/dist'
