# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - cli/
    - '**/readme.md'

variables:
- name: packageName
  value: blackboardlib

jobs:
- job: Build_Library
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  # - task: NodeTool@0
  #   inputs:
  #     versionSpec: '11.x'
  #   displayName: 'Install Node.js'

  - script: |
        latestVersion=`npm show $(packageName) version`
        IFS=. read major minor patch <<<"${latestVersion}"
        echo "Major: ${major}"
        echo "Minor: ${minor}"
        echo "Patch: ${patch}"
        echo '##vso[task.setvariable variable=major]'$major
        echo '##vso[task.setvariable variable=minor]'$minor
        echo '##vso[task.setvariable variable=patch]'$patch
    displayName: Set version variables

  - script: |
        echo "Major: ${major}"
        echo "Minor: ${minor}"
        echo "Patch: ${patch}"

  # - script: |
  #     npm install
  #     npm run build
  #   displayName: 'npm install and build'

  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     ArtifactName: 'lib'
  #     PathtoPublish: '$(Build.SourcesDirectory)/dist'
